package i5.las2peer.services.philos;


import java.net.HttpURLConnection;

import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.Consumes;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.MediaType;

import i5.las2peer.api.Context;
import i5.las2peer.api.ManualDeployment;
import i5.las2peer.api.ServiceException;
import i5.las2peer.api.logging.MonitoringEvent;
import i5.las2peer.restMapper.RESTService;
import i5.las2peer.restMapper.annotations.ServicePath;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Contact;
import io.swagger.annotations.Info;
import io.swagger.annotations.License;
import io.swagger.annotations.SwaggerDefinition;
import org.json.simple.*;

import java.util.HashMap;
import java.util.Map;
 

/**
 *
 * 28
 *
 * This microservice was generated by the CAE (Community Application Editor). If you edit it, please
 * make sure to keep the general structure of the file and only add the body of the methods provided
 * in this main file. Private methods are also allowed, but any "deeper" functionality should be
 * outsourced to (imported) classes.
 *
 */
@ServicePath("poems")
@ManualDeployment
public class Philos extends RESTService {





  public Philos() {
	super();
    // read and set properties values
    setFieldValues();
    
  }

  @Override
  public void initResources() {
	getResourceConfig().register(RootResource.class);
  }

  // //////////////////////////////////////////////////////////////////////////////////////
  // REST methods
  // //////////////////////////////////////////////////////////////////////////////////////

  @Api
  @SwaggerDefinition(
      info = @Info(title = "28", version = "",
          description = "",
          termsOfService = "",
          contact = @Contact(name = "me", email = "CAEAddress@gmail.com") ,
          license = @License(name = "BSD",
              url = "https://github.com/CAETESTRWTH/microservice-28/blob/master/LICENSE.txt") ) )
  @Path("/")
  public static class RootResource {

    private final Philos service = (Philos) Context.getCurrent().getService();

      /**
   * 
   * getPoemsTwo
   *
   * 
   *
   * 
   * @return Response 
   * 
   */
  @GET
  @Path("/poemstwo")
  @Produces(MediaType.APPLICATION_JSON)
  @Consumes(MediaType.TEXT_PLAIN)
  @ApiResponses(value = {
       @ApiResponse(code = HttpURLConnection.HTTP_OK, message = "response")
  })
  @ApiOperation(value = "getPoemsTwo", notes = " ")
  public Response getPoemsTwo() {




     
    // service method invocations

     




    // response
    boolean response_condition = true;
    if(response_condition) {
      JSONObject result = new JSONObject();

 JSONArray a = new JSONArray();    
JSONObject temp = new JSONObject(); 
temp.put("text", "Hast du eine große Freude an etwas gehabt, so nimm Abschied! Nie kommt es zum zweiten Male.");    
JSONObject temp2 = new JSONObject(); 
temp2.put("text", "Das Bewusstsein der Vergänglichkeit, vereint mit der Berücksichtigung des enormen Potenzials der menschlichen Existenz, verleiht uns ein Gefühl der Dringlichkeit.");  
JSONObject temp3 = new JSONObject(); 
temp2.put("text", "Keine Kunst ist's, alt zu werden; es ist Kunst, es zu ertragen."); 
a.add(temp);
a.add(temp2);
a.add(temp3);

      return Response.ok(a.toJSONString()).build();
    }
    return null;
  }



  }

  // //////////////////////////////////////////////////////////////////////////////////////
  // Service methods (for inter service calls)
  // //////////////////////////////////////////////////////////////////////////////////////
  
  

  // //////////////////////////////////////////////////////////////////////////////////////
  // Custom monitoring message descriptions (can be called via RMI)
  // //////////////////////////////////////////////////////////////////////////////////////

  public Map<String, String> getCustomMessageDescriptions() {
    Map<String, String> descriptions = new HashMap<>();
    
    return descriptions;
  }

}
